---
title: "State College Restaurants"
author: "Group 3"
date: "12/31/2020"
output: ioslides_presentation
---

## Introduction

```{r, frontMatter}
library(tidyverse)
library(httr)
library(readr)
library(ggplot2)
```


```{r, api}
client_id <- read_file("api_id.txt")
client_secret <- read_file("api_key.txt")

res <- POST("https://api.yelp.com/oauth2/token",
            body = list(grant_type = "client_credentials",
                        client_id = client_id,
                        client_secret = client_secret))

token <- content(res)$access_token
```

```{r, getData}
yelp <- "https://api.yelp.com"
term <- "food"
location <- "State College, PA"
categories <- NULL
limit <- 50
radius <- 2000
url <- modify_url(yelp, path = c("v3", "businesses", "search"),
                  query = list(term = term, location = location, 
                               limit = limit,
                               radius = radius))
res <- GET(url, add_headers('Authorization' = paste("bearer", client_secret)))

results <- content(res)



yelp_httr_parse <- function(x) {

  parse_list <- list(id = x$id, 
                     name = x$name, 
                     rating = x$rating, 
                     review_count = x$review_count, 
                     latitude = x$coordinates$latitude, 
                     longitude = x$coordinates$longitude, 
                     address1 = x$location$address1, 
                     city = x$location$city, 
                     state = x$location$state, 
                     distance = x$distance)
  
  parse_list <- lapply(parse_list, FUN = function(x) ifelse(is.null(x), "", x))
  
  df <- tibble(id=parse_list$id,
                   name=parse_list$name, 
                   rating = parse_list$rating, 
                   review_count = parse_list$review_count, 
                   latitude=parse_list$latitude, 
                   longitude = parse_list$longitude, 
                   address1 = parse_list$address1, 
                   city = parse_list$city, 
                   state = parse_list$state, 
                   distance= parse_list$distance)
  df
}

results_list <- lapply(results$businesses, FUN = yelp_httr_parse)

restaurants <- do.call("rbind", results_list)
```


## Overview of food-related business

Variables:
```{r}
names(restaurants)
```

### Overall Ratings

```{r}
summary(restaurants$rating)

ggplot(restaurants, aes(y = rating)) + geom_boxplot() + theme_minimal()
ggplot(restaurants, aes(x = rating)) + geom_histogram(binwidth = 1, fill = "orange", col = "black", boundary = 0) + xlim(0,5) + theme_minimal()
```

At first glance, it seems people generally enjoy the restaurants, with a median rating of 4 stars, and none below 2.5.

However, we have not taken into account the number of reviews that these restaurants received.
```{r}
summary(restaurants$review_count)
```



